BOARD_CHOICES = [
    (1, "Central Board of Secondary Education (CBSE)"),
    (2, "Council for the Indian School Certificate Examinations (CISCE)"),
    (3, "National Institute of Open Schooling (NIOS)"),
    (4, "Andhra Pradesh Board of Secondary Education (BSEAP)"),
    (5, "Board of Intermediate Education Andhra Pradesh (BIEAP)"),
    (6, "Assam Higher Secondary Education Council (AHSEC)"),
    (7, "Board of Secondary Education Assam (SEBA)"),
    (8, "Bihar School Examination Board (BSEB)"),
    (9, "Chhattisgarh Board of Secondary Education (CGBSE)"),
    (10, "Chhattisgarh State Open School (CGSOS)"),
    (11, "Goa Board of Secondary and Higher Secondary Education (GBSHSE)"),
    (12, "Gujarat Secondary and Higher Secondary Education Board (GSEB)"),
    (13, "Board of School Education Haryana (HBSE)"),
    (14, "Himachal Pradesh Board of School Education (HPBOSE)"),
    (15, "Jammu and Kashmir Board of School Education (JKBOSE)"),
    (16, "Jharkhand Academic Council (JAC)"),
    (17, "Karnataka Secondary Education Examination Board (KSEEB)"),
    (18, "Department of Pre-University Education, Karnataka (PUE Karnataka)"),
    (19, "Kerala Board of Public Examinations (KBPE)"),
    (20, "Madhya Pradesh Board of Secondary Education (MPBSE)"),
    (21, "Maharashtra State Board of Secondary and Higher Secondary Education (MSBSHSE)"),
    (22, "Manipur Board of Secondary Education (BSEM)"),
    (23, "Council of Higher Secondary Education Manipur (COHSEM)"),
    (24, "Meghalaya Board of School Education (MBOSE)"),
    (25, "Mizoram Board of School Education (MBSE)"),
    (26, "Nagaland Board of School Education (NBSE)"),
    (27, "Odisha Board of Secondary Education (BSE Odisha)"),
    (28, "Council of Higher Secondary Education, Odisha (CHSE Odisha)"),
    (29, "Punjab School Education Board (PSEB)"),
    (30, "Rajasthan Board of Secondary Education (RBSE)"),
    (31, "Tamil Nadu State Board (TNBSE)"),
    (32, "Telangana Board of Secondary Education (BSE Telangana)"),
    (33, "Telangana State Board of Intermediate Education (TSBIE)"),
    (34, "Tripura Board of Secondary Education (TBSE)"),
    (35, "Uttar Pradesh Madhyamik Shiksha Parishad (UPMSP)"),
    (36, "Uttarakhand Board of School Education (UBSE)"),
    (37, "West Bengal Board of Secondary Education (WBBSE)"),
    (38, "West Bengal Council of Higher Secondary Education (WBCHSE)"),
    (39, "State Council of Educational Research and Training (SCERT) Various States"),
]

YEAR_CHOICES =[
    (2023, "2023"),
    (2022, "2022"),
    (2021, "2021"),
    (2020, "2020"),
    (2019, "2019"),
    (2018, "2018"),
    (2017, "2017"),
    (2016, "2016"),
    (2015, "2015"),
    (2014, "2014"),
    (2013, "2013"),
    (2012, "2012"),
    (2011, "2011"),
    (2010, "2010"),
    (2009, "2009"),
    (2008, "2008"),
    (2007, "2007"),
    (2006, "2006"),
    (2005, "2005"),
    (2004, "2004"),
    (2003, "2003"),
    (2002, "2002"),
    (2001, "2001"),
    (2000, "2000"),
]