# Generated by Django 5.1.7 on 2025-03-15 00:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0002_alter_department_code'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('PR', 'Permanent'), ('PS', 'Present')], max_length=2)),
                ('address', models.TextField()),
                ('city', models.CharField(max_length=50)),
                ('state', models.CharField(choices=[('AN', 'Andaman and Nicobar Islands'), ('AP', 'Andhra Pradesh'), ('AR', 'Arunachal Pradesh'), ('AS', 'Assam'), ('BR', 'Bihar'), ('CH', 'Chandigarh'), ('CG', 'Chhattisgarh'), ('DD', 'Dadra and Nagar Haveli'), ('DL', 'Delhi'), ('GA', 'Goa'), ('GJ', 'Gujarat'), ('HR', 'Haryana'), ('HP', 'Himachal Pradesh'), ('JK', 'Jammu and Kashmir'), ('JH', 'Jharkhand'), ('KA', 'Karnataka'), ('KL', 'Kerala'), ('LD', 'Lakshadweep'), ('MP', 'Madhya Pradesh'), ('MH', 'Maharashtra'), ('MN', 'Manipur'), ('ML', 'Meghalaya'), ('MZ', 'Mizoram'), ('NL', 'Nagaland'), ('OR', 'Odisha'), ('PY', 'Puducherry'), ('WB', 'West Bengal')], max_length=3)),
                ('pincode', models.CharField(max_length=10)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='address', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester', models.IntegerField()),
                ('class_roll', models.PositiveIntegerField()),
                ('uni_roll', models.PositiveIntegerField(blank=True, null=True, unique=True)),
                ('reg_no', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('class_10', models.JSONField(blank=True, null=True)),
                ('class_12', models.JSONField(blank=True, null=True)),
                ('ug', models.JSONField(blank=True, null=True)),
                ('pg', models.JSONField(blank=True, null=True)),
                ('father_name', models.CharField(blank=True, max_length=150, null=True)),
                ('father_phone', models.CharField(blank=True, max_length=15, null=True)),
                ('father_profession', models.CharField(blank=True, max_length=150, null=True)),
                ('father_income', models.BigIntegerField(blank=True, null=True)),
                ('mother_name', models.CharField(blank=True, max_length=150, null=True)),
                ('mother_phone', models.CharField(blank=True, max_length=15, null=True)),
                ('mother_profession', models.CharField(blank=True, max_length=150, null=True)),
                ('mother_income', models.BigIntegerField(blank=True, null=True)),
                ('admission_date', models.DateTimeField()),
                ('step', models.IntegerField(default=1)),
                ('academic_year', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='academics.academicyear')),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='academics.course')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
