# Generated by Django 5.1.7 on 2025-03-09 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='type',
            field=models.CharField(choices=[('AD', 'Admin'), ('TE', 'Teacher'), ('ST', 'Student'), ('SF', 'Staff')], default='ST', max_length=5),
        ),
    ]
