# Generated by Django 5.1.7 on 2025-03-12 23:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0013_department_is_academic'),
        ('accounts', '0005_remove_student_semester_student_grade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='type',
            field=models.CharField(choices=[('AD', 'Admin'), ('TE', 'Teacher'), ('ST', 'Student'), ('HR', 'Human Resource'), ('AD', 'Admission'), ('AC', 'Accounant'), ('RP', 'Receptionist')], default='ST', max_length=5),
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(max_length=150)),
                ('department', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='academics.department')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
