# Generated by Django 5.1.7 on 2025-03-10 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0002_session'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Session',
            new_name='AcademicYear',
        ),
    ]
