# Generated by Django 5.1.7 on 2025-03-10 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0003_rename_session_academicyear'),
    ]

    operations = [
        migrations.AddField(
            model_name='academicyear',
            name='is_open',
            field=models.BooleanField(default=False),
        ),
    ]
