# Generated by Django 5.1.7 on 2025-03-17 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0005_alter_schedule_unique_together'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='department',
            name='is_academic',
        ),
        migrations.AddField(
            model_name='department',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
