# Generated by Django 5.1.7 on 2025-03-11 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0006_subject'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Subject',
        ),
    ]
