# Generated by Django 5.1.7 on 2025-03-17 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0006_remove_department_is_academic_department_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='system',
            field=models.CharField(choices=[('SEM', 'Semester'), ('ANL', 'Anual')], default='SEM', max_length=5),
        ),
        migrations.AlterField(
            model_name='course',
            name='duration',
            field=models.CharField(max_length=50),
        ),
    ]
