# Generated by Django 5.1.7 on 2025-03-12 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0008_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
