# Generated by Django 5.1.7 on 2025-03-12 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0009_subject_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='grade',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
