# Generated by Django 5.1.7 on 2025-03-12 08:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0010_grade_status'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='grade',
            unique_together={('course', 'number')},
        ),
    ]
