# Generated by Django 5.1.7 on 2025-03-12 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0011_alter_grade_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grade',
            name='name',
            field=models.CharField(choices=[('SEM', 'Semester')], max_length=5),
        ),
        migrations.AlterField(
            model_name='grade',
            name='number',
            field=models.IntegerField(choices=[(1, 'Semester 1'), (2, 'Semester 2'), (3, 'Semester 3'), (4, 'Semester 4'), (5, 'Semester 5'), (6, 'Semester 6'), (7, 'Semester 7'), (8, 'Semester 8')]),
        ),
    ]
