# Generated by Django 5.1.7 on 2025-03-12 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0012_alter_grade_name_alter_grade_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='is_academic',
            field=models.BooleanField(default=False),
        ),
    ]
